// 世界主要沿海港口数据库 - 按区域分类
// 用于航海日记的港口自动补全功能
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// 中国主要港口
const chinaPorts = [
  { name: '上海', english: 'Shanghai', country: '中国', pinyin: 'SH' },
  { name: '宁波舟山', english: 'Ningbo Zhoushan', country: '中国', pinyin: 'NBZS' },
  { name: '深圳', english: 'Shenzhen', country: '中国', pinyin: 'SZ' },
  { name: '广州', english: 'Guangzhou', country: '中国', pinyin: 'GZ' },
  { name: '青岛', english: 'Qingdao', country: '中国', pinyin: 'QD' },
  { name: '天津', english: 'Tianjin', country: '中国', pinyin: 'TJ' },
  { name: '大连', english: 'Dalian', country: '中国', pinyin: 'DL' },
  { name: '厦门', english: 'Xiamen', country: '中国', pinyin: 'XM' },
  { name: '福州', english: 'Fuzhou', country: '中国', pinyin: 'FZ' },
  { name: '海口', english: 'Haikou', country: '中国', pinyin: 'HK' },
  { name: '湛江', english: 'Zhanjiang', country: '中国', pinyin: 'ZJ' },
  { name: '珠海', english: 'Zhuhai', country: '中国', pinyin: 'ZH' },
  { name: '汕头', english: 'Shantou', country: '中国', pinyin: 'ST' },
  { name: '北海', english: 'Beihai', country: '中国', pinyin: 'BH' },
  { name: '防城港', english: 'Fangchenggang', country: '中国', pinyin: 'FCG' },
  { name: '钦州', english: 'Qinzhou', country: '中国', pinyin: 'QZ' },
  { name: '温州', english: 'Wenzhou', country: '中国', pinyin: 'WZ' },
  { name: '台州', english: 'Taizhou', country: '中国', pinyin: 'TZ' },
  { name: '连云港', english: 'Lianyungang', country: '中国', pinyin: 'LYG' },
  { name: '烟台', english: 'Yantai', country: '中国', pinyin: 'YT' },
  { name: '威海', english: 'Weihai', country: '中国', pinyin: 'WH' },
  { name: '秦皇岛', english: 'Qinhuangdao', country: '中国', pinyin: 'QHD' },
  { name: '营口', english: 'Yingkou', country: '中国', pinyin: 'YK' },
  { name: '锦州', english: 'Jinzhou', country: '中国', pinyin: 'JZ' },
  { name: '丹东', english: 'Dandong', country: '中国', pinyin: 'DD' },
  { name: '南通', english: 'Nantong', country: '中国', pinyin: 'NT' },
  { name: '张家港', english: 'Zhangjiagang', country: '中国', pinyin: 'ZJG' },
  { name: '江阴', english: 'Jiangyin', country: '中国', pinyin: 'JY' },
  { name: '常熟', english: 'Changshu', country: '中国', pinyin: 'CS' },
  { name: '太仓', english: 'Taicang', country: '中国', pinyin: 'TC' },
  { name: '镇江', english: 'Zhenjiang', country: '中国', pinyin: 'ZJ' },
  { name: '南京', english: 'Nanjing', country: '中国', pinyin: 'NJ' },
  { name: '芜湖', english: 'Wuhu', country: '中国', pinyin: 'WH' },
  { name: '马鞍山', english: 'Maanshan', country: '中国', pinyin: 'MAS' },
  { name: '铜陵', english: 'Tongling', country: '中国', pinyin: 'TL' },
  { name: '安庆', english: 'Anqing', country: '中国', pinyin: 'AQ' },
  { name: '九江', english: 'Jiujiang', country: '中国', pinyin: 'JJ' },
  { name: '黄石', english: 'Huangshi', country: '中国', pinyin: 'HS' },
  { name: '武汉', english: 'Wuhan', country: '中国', pinyin: 'WH' },
  { name: '岳阳', english: 'Yueyang', country: '中国', pinyin: 'YY' },
  { name: '城陵矶', english: 'Chenglingji', country: '中国', pinyin: 'CLJ' },
];

// 东南亚港口
const southeastAsiaPorts = [
  { name: '新加坡', english: 'Singapore', country: '新加坡', pinyin: 'XJP' },
  { name: '巴生', english: 'Port Klang', country: '马来西亚', pinyin: 'BS' },
  { name: '丹绒帕拉帕斯', english: 'Tanjung Pelepas', country: '马来西亚', pinyin: 'TJPLP' },
  { name: '槟城', english: 'Penang', country: '马来西亚', pinyin: 'BC' },
  { name: '巴西古当', english: 'Pasir Gudang', country: '马来西亚', pinyin: 'BXGD' },
  { name: '关丹', english: 'Kuantan', country: '马来西亚', pinyin: 'GD' },
  { name: '民都鲁', english: 'Bintulu', country: '马来西亚', pinyin: 'MDL' },
  { name: '古晋', english: 'Kuching', country: '马来西亚', pinyin: 'GJ' },
  { name: '马尼拉', english: 'Manila', country: '菲律宾', pinyin: 'MNL' },
  { name: '宿务', english: 'Cebu', country: '菲律宾', pinyin: 'SW' },
  { name: '达沃', english: 'Davao', country: '菲律宾', pinyin: 'DW' },
  { name: '雅加达', english: 'Jakarta', country: '印度尼西亚', pinyin: 'YJD' },
  { name: '泗水', english: 'Surabaya', country: '印度尼西亚', pinyin: 'SS' },
  { name: '巴厘巴板', english: 'Balikpapan', country: '印度尼西亚', pinyin: 'BLBP' },
  { name: '望加锡', english: 'Makassar', country: '印度尼西亚', pinyin: 'WJS' },
  { name: '三宝垄', english: 'Semarang', country: '印度尼西亚', pinyin: 'SBL' },
  { name: '坤甸', english: 'Pontianak', country: '印度尼西亚', pinyin: 'KD' },
  { name: '巴淡岛', english: 'Batam', country: '印度尼西亚', pinyin: 'BD' },
  { name: '海防', english: 'Hai Phong', country: '越南', pinyin: 'HF' },
  { name: '胡志明', english: 'Ho Chi Minh City', country: '越南', pinyin: 'HZM' },
  { name: '岘港', english: 'Da Nang', country: '越南', pinyin: 'XG' },
  { name: '归仁', english: 'Quy Nhon', country: '越南', pinyin: 'GR' },
  { name: '头顿', english: 'Vung Tau', country: '越南', pinyin: 'TD' },
  { name: '林查班', english: 'Laem Chabang', country: '泰国', pinyin: 'LCB' },
  { name: '曼谷', english: 'Bangkok', country: '泰国', pinyin: 'MG' },
  { name: '宋卡', english: 'Songkhla', country: '泰国', pinyin: 'SK' },
  { name: '普吉', english: 'Phuket', country: '泰国', pinyin: 'PJ' },
  { name: '春武里', english: 'Chonburi', country: '泰国', pinyin: 'CWL' },
  { name: '西哈努克', english: 'Sihanoukville', country: '柬埔寨', pinyin: 'XHNK' },
  { name: '金边', english: 'Phnom Penh', country: '柬埔寨', pinyin: 'JB' },
  { name: '仰光', english: 'Yangon', country: '缅甸', pinyin: 'YG' },
  { name: '丹老', english: 'Mawlamyine', country: '缅甸', pinyin: 'DL' },
];

// 东亚港口（日本、韩国）
const eastAsiaPorts = [
  { name: '东京', english: 'Tokyo', country: '日本', pinyin: 'DJ' },
  { name: '横滨', english: 'Yokohama', country: '日本', pinyin: 'HY' },
  { name: '名古屋', english: 'Nagoya', country: '日本', pinyin: 'MGW' },
  { name: '大阪', english: 'Osaka', country: '日本', pinyin: 'DB' },
  { name: '神户', english: 'Kobe', country: '日本', pinyin: 'SH' },
  { name: '釜山', english: 'Busan', country: '韩国', pinyin: 'FS' },
  { name: '长崎', english: 'Nagasaki', country: '日本', pinyin: 'CQ' },
  { name: '博多', english: 'Hakata', country: '日本', pinyin: 'BD' },
  { name: '广岛', english: 'Hiroshima', country: '日本', pinyin: 'GD' },
  { name: '清水', english: 'Shimizu', country: '日本', pinyin: 'QS' },
  { name: '千叶', english: 'Chiba', country: '日本', pinyin: 'QY' },
  { name: '新潟', english: 'Niigata', country: '日本', pinyin: 'XX' },
  { name: '富山', english: 'Toyama', country: '日本', pinyin: 'FS' },
  { name: '福冈', english: 'Fukuoka', country: '日本', pinyin: 'FG' },
  { name: '川崎', english: 'Kawasaki', country: '日本', pinyin: 'CQ' },
  { name: '北九州', english: 'Kitakyushu', country: '日本', pinyin: 'BJZ' },
  { name: '鹿儿岛', english: 'Kagoshima', country: '日本', pinyin: 'LEJ' },
  { name: '那霸', english: 'Naha', country: '日本', pinyin: 'NB' },
  { name: '仁川', english: 'Incheon', country: '韩国', pinyin: 'RC' },
  { name: '蔚山', english: 'Ulsan', country: '韩国', pinyin: 'WS' },
  { name: '光阳', english: 'Gwangyang', country: '韩国', pinyin: 'GY' },
  { name: '群山', english: 'Gunsan', country: '韩国', pinyin: 'QS' },
  { name: '丽水', english: 'Yeosu', country: '韩国', pinyin: 'LS' },
];

// 中东港口
const middleEastPorts = [
  { name: '迪拜', english: 'Dubai', country: '阿联酋', pinyin: 'DB' },
  { name: '杰布阿里', english: 'Jebel Ali', country: '阿联酋', pinyin: 'JBAL' },
  { name: '阿布扎比', english: 'Abu Dhabi', country: '阿联酋', pinyin: 'ABZB' },
  { name: '沙迦', english: 'Sharjah', country: '阿联酋', pinyin: 'SG' },
  { name: '富查伊拉', english: 'Fujairah', country: '阿联酋', pinyin: 'FCL' },
  { name: '达曼', english: 'Dammam', country: '沙特阿拉伯', pinyin: 'DM' },
  { name: '吉达', english: 'Jeddah', country: '沙特阿拉伯', pinyin: 'JD' },
  { name: '延布', english: 'Yanbu', country: '沙特阿拉伯', pinyin: 'YB' },
  { name: '拉斯坦努拉', english: 'Ras Tanura', country: '沙特阿拉伯', pinyin: 'LSTNL' },
  { name: '阿巴斯', english: 'Bandar Abbas', country: '伊朗', pinyin: 'AB' },
  { name: '霍拉姆沙赫尔', english: 'Khorramshahr', country: '伊朗', pinyin: 'HLMSHE' },
  { name: '阿巴丹', english: 'Abadan', country: '伊朗', pinyin: 'ABD' },
  { name: '布什尔', english: 'Bushehr', country: '伊朗', pinyin: 'BSE' },
  { name: '荷台达', english: 'Hodeidah', country: '也门', pinyin: 'HTD' },
  { name: '亚丁', english: 'Aden', country: '也门', pinyin: 'YD' },
  { name: '穆卡拉', english: 'Mukalla', country: '也门', pinyin: 'MKL' },
  { name: '马斯喀特', english: 'Muscat', country: '阿曼', pinyin: 'MSK' },
  { name: '苏哈尔', english: 'Sohar', country: '阿曼', pinyin: 'SHE' },
  { name: '萨拉拉', english: 'Salalah', country: '阿曼', pinyin: 'SLL' },
  { name: '杜库姆', english: 'Duqm', country: '阿曼', pinyin: 'DKM' },
  { name: '多哈', english: 'Doha', country: '卡塔尔', pinyin: 'DH' },
  { name: '科威特', english: 'Kuwait', country: '科威特', pinyin: 'KWT' },
  { name: '巴林', english: 'Bahrain', country: '巴林', pinyin: 'BL' },
  { name: '阿卡巴', english: 'Aqaba', country: '约旦', pinyin: 'AKB' },
  { name: '阿什杜德', english: 'Ashdod', country: '以色列', pinyin: 'ASD' },
  { name: '海法', english: 'Haifa', country: '以色列', pinyin: 'HF' },
  { name: '埃拉特', english: 'Eilat', country: '以色列', pinyin: 'ALT' },
  { name: '贝鲁特', english: 'Beirut', country: '黎巴嫩', pinyin: 'BLT' },
];

// 南亚港口
const southAsiaPorts = [
  { name: '孟买', english: 'Mumbai', country: '印度', pinyin: 'MM' },
  { name: '那瓦西瓦', english: 'Nhava Sheva', country: '印度', pinyin: 'NWSW' },
  { name: '加尔各答', english: 'Kolkata', country: '印度', pinyin: 'JGED' },
  { name: '钦奈', english: 'Chennai', country: '印度', pinyin: 'QN' },
  { name: '维沙卡帕特南', english: 'Visakhapatnam', country: '印度', pinyin: 'WSKPTN' },
  { name: '杜蒂戈林', english: 'Tuticorin', country: '印度', pinyin: 'DTGL' },
  { name: '柯钦', english: 'Cochin', country: '印度', pinyin: 'KQ' },
  { name: '坎德拉', english: 'Kandla', country: '印度', pinyin: 'KDL' },
  { name: '蒙德拉', english: 'Mundra', country: '印度', pinyin: 'MDL' },
  { name: '皮帕瓦夫', english: 'Pipavav', country: '印度', pinyin: 'PPWF' },
  { name: '维泽', english: 'Vizag', country: '印度', pinyin: 'WZ' },
  { name: '芒格洛尔', english: 'Mangalore', country: '印度', pinyin: 'MGLR' },
  { name: '科伦坡', english: 'Colombo', country: '斯里兰卡', pinyin: 'KLP' },
  { name: '汉班托塔', english: 'Hambantota', country: '斯里兰卡', pinyin: 'HBTT' },
  { name: '卡拉奇', english: 'Karachi', country: '巴基斯坦', pinyin: 'KLQ' },
  { name: '卡西姆', english: 'Port Qasim', country: '巴基斯坦', pinyin: 'KXM' },
  { name: '瓜达尔', english: 'Gwadar', country: '巴基斯坦', pinyin: 'GDE' },
  { name: '吉大港', english: 'Chittagong', country: '孟加拉国', pinyin: 'JDK' },
  { name: '蒙格拉', english: 'Mongla', country: '孟加拉国', pinyin: 'MGL' },
];

// 欧洲港口
const europePorts = [
  { name: '鹿特丹', english: 'Rotterdam', country: '荷兰', pinyin: 'LTD' },
  { name: '安特卫普', english: 'Antwerp', country: '比利时', pinyin: 'ATWP' },
  { name: '汉堡', english: 'Hamburg', country: '德国', pinyin: 'HB' },
  { name: '不来梅哈芬', english: 'Bremerhaven', country: '德国', pinyin: 'BLMHF' },
  { name: '勒阿弗尔', english: 'Le Havre', country: '法国', pinyin: 'LHF' },
  { name: '马赛', english: 'Marseille', country: '法国', pinyin: 'MS' },
  { name: '福斯', english: 'Fos-sur-Mer', country: '法国', pinyin: 'FS' },
  { name: '敦刻尔克', english: 'Dunkirk', country: '法国', pinyin: 'DNK' },
  { name: '伦敦', english: 'London', country: '英国', pinyin: 'LD' },
  { name: '费利克斯托', english: 'Felixstowe', country: '英国', pinyin: 'FLKST' },
  { name: '南安普敦', english: 'Southampton', country: '英国', pinyin: 'NAD' },
  { name: '利物浦', english: 'Liverpool', country: '英国', pinyin: 'LP' },
  { name: '格拉斯哥', english: 'Glasgow', country: '英国', pinyin: 'GLSG' },
  { name: '阿尔赫西拉斯', english: 'Algeciras', country: '西班牙', pinyin: 'AJHSL' },
  { name: '巴塞罗那', english: 'Barcelona', country: '西班牙', pinyin: 'BXLN' },
  { name: '巴伦西亚', english: 'Valencia', country: '西班牙', pinyin: 'BLX' },
  { name: '毕尔巴鄂', english: 'Bilbao', country: '西班牙', pinyin: 'BEBE' },
  { name: '热那亚', english: 'Genoa', country: '意大利', pinyin: 'RNY' },
  { name: '那不勒斯', english: 'Naples', country: '意大利', pinyin: 'NBLS' },
  { name: '里窝那', english: 'Livorno', country: '意大利', pinyin: 'LW' },
  { name: '威尼斯', english: 'Venice', country: '意大利', pinyin: 'WNS' },
  { name: '的里雅斯特', english: 'Trieste', country: '意大利', pinyin: 'DLST' },
  { name: '萨莱诺', english: 'Salerno', country: '意大利', pinyin: 'SLN' },
  { name: '塔兰托', english: 'Taranto', country: '意大利', pinyin: 'TLT' },
  { name: '比雷埃夫斯', english: 'Piraeus', country: '希腊', pinyin: 'BLAF' },
  { name: '塞萨洛尼基', english: 'Thessaloniki', country: '希腊', pinyin: 'SSLNK' },
  { name: '康斯坦察', english: 'Constanta', country: '罗马尼亚', pinyin: 'KSTC' },
  { name: '格但斯克', english: 'Gdansk', country: '波兰', pinyin: 'GDSK' },
  { name: '格丁尼亚', english: 'Gdynia', country: '波兰', pinyin: 'GDNY' },
  { name: '圣彼得堡', english: 'St. Petersburg', country: '俄罗斯', pinyin: 'STP' },
  { name: '加里宁格勒', english: 'Kaliningrad', country: '俄罗斯', pinyin: 'JLNL' },
  { name: '新罗西斯克', english: 'Novorossiysk', country: '俄罗斯', pinyin: 'XLSSK' },
  { name: '海参崴', english: 'Vladivostok', country: '俄罗斯', pinyin: 'HSW' },
  { name: '纳霍德卡', english: 'Nakhodka', country: '俄罗斯', pinyin: 'NHDK' },
  { name: '东方港', english: 'Vostochny', country: '俄罗斯', pinyin: 'DFG' },
  { name: '哥德堡', english: 'Gothenburg', country: '瑞典', pinyin: 'GDB' },
  { name: '赫尔辛基', english: 'Helsinki', country: '芬兰', pinyin: 'HEXJ' },
  { name: '奥斯陆', english: 'Oslo', country: '挪威', pinyin: 'ASL' },
  { name: '都柏林', english: 'Dublin', country: '爱尔兰', pinyin: 'DBL' },
  { name: '阿姆斯特丹', english: 'Amsterdam', country: '荷兰', pinyin: 'AMST' },
];

// 非洲港口
const africaPorts = [
  { name: '德班', english: 'Durban', country: '南非', pinyin: 'DB' },
  { name: '开普敦', english: 'Cape Town', country: '南非', pinyin: 'KPD' },
  { name: '伊丽莎白港', english: 'Port Elizabeth', country: '南非', pinyin: 'ILSZB' },
  { name: '理查兹湾', english: 'Richards Bay', country: '南非', pinyin: 'LZHW' },
  { name: '拉各斯', english: 'Lagos', country: '尼日利亚', pinyin: 'LGS' },
  { name: '阿帕帕', english: 'Apapa', country: '尼日利亚', pinyin: 'PP' },
  { name: '廷坎岛', english: 'Tin Can Island', country: '尼日利亚', pinyin: 'TKD' },
  { name: '科托努', english: 'Cotonou', country: '贝宁', pinyin: 'KTN' },
  { name: '特马', english: 'Tema', country: '加纳', pinyin: 'TM' },
  { name: '阿克拉', english: 'Accra', country: '加纳', pinyin: 'AKL' },
  { name: '塔科拉迪', english: 'Takoradi', country: '加纳', pinyin: 'TKLD' },
  { name: '阿比让', english: 'Abidjan', country: '科特迪瓦', pinyin: 'ABR' },
  { name: '达喀尔', english: 'Dakar', country: '塞内加尔', pinyin: 'DKE' },
  { name: '蒙巴萨', english: 'Mombasa', country: '肯尼亚', pinyin: 'MBS' },
  { name: '达累斯萨拉姆', english: 'Dar es Salaam', country: '坦桑尼亚', pinyin: 'DLSLM' },
  { name: '坦噶', english: 'Tanga', country: '坦桑尼亚', pinyin: 'TG' },
  { name: '桑给巴尔', english: 'Zanzibar', country: '坦桑尼亚', pinyin: 'SJBE' },
  { name: '贝拉', english: 'Beira', country: '莫桑比克', pinyin: 'BL' },
  { name: '马普托', english: 'Maputo', country: '莫桑比克', pinyin: 'MPT' },
  { name: '卢安达', english: 'Luanda', country: '安哥拉', pinyin: 'LWD' },
  { name: '洛比托', english: 'Lobito', country: '安哥拉', pinyin: 'LBT' },
  { name: '索韦托', english: 'Soweto', country: '南非', pinyin: 'SWT' },
  { name: '纳卡拉', english: 'Nacala', country: '莫桑比克', pinyin: 'NKL' },
  { name: '鲸湾港', english: 'Walvis Bay', country: '纳米比亚', pinyin: 'JWG' },
  { name: '吕德里茨', english: 'Luderitz', country: '纳米比亚', pinyin: 'LDLC' },
  { name: '阿尔及尔', english: 'Algiers', country: '阿尔及利亚', pinyin: 'AJE' },
  { name: '奥兰', english: 'Oran', country: '阿尔及利亚', pinyin: 'AL' },
  { name: '卡萨布兰卡', english: 'Casablanca', country: '摩洛哥', pinyin: 'KSBLK' },
  { name: '丹吉尔', english: 'Tangier', country: '摩洛哥', pinyin: 'TJ' },
  { name: '突尼斯', english: 'Tunis', country: '突尼斯', pinyin: 'TNS' },
  { name: '的黎波里', english: 'Tripoli', country: '利比亚', pinyin: 'DLP' },
  { name: '班加西', english: 'Benghazi', country: '利比亚', pinyin: 'BJX' },
  { name: '亚历山大', english: 'Alexandria', country: '埃及', pinyin: 'YLDG' },
  { name: '塞得港', english: 'Port Said', country: '埃及', pinyin: 'SDG' },
  { name: '苏伊士', english: 'Suez', country: '埃及', pinyin: 'SYS' },
];

// 美洲港口
const americasPorts = [
  { name: '洛杉矶', english: 'Los Angeles', country: '美国', pinyin: 'LSJ' },
  { name: '长滩', english: 'Long Beach', country: '美国', pinyin: 'CT' },
  { name: '西雅图', english: 'Seattle', country: '美国', pinyin: 'XYT' },
  { name: '塔科马', english: 'Tacoma', country: '美国', pinyin: 'TKM' },
  { name: '旧金山', english: 'San Francisco', country: '美国', pinyin: 'JJS' },
  { name: '奥克兰', english: 'Oakland', country: '美国', pinyin: 'AKL' },
  { name: '圣地亚哥', english: 'San Diego', country: '美国', pinyin: 'SYJG' },
  { name: '休斯顿', english: 'Houston', country: '美国', pinyin: 'XSD' },
  { name: '新奥尔良', english: 'New Orleans', country: '美国', pinyin: 'XAEL' },
  { name: '莫比尔', english: 'Mobile', country: '美国', pinyin: 'MBE' },
  { name: '坦帕', english: 'Tampa', country: '美国', pinyin: 'TP' },
  { name: '杰克逊维尔', english: 'Jacksonville', country: '美国', pinyin: 'JKSW' },
  { name: '迈阿密', english: 'Miami', country: '美国', pinyin: 'MAM' },
  { name: '查尔斯顿', english: 'Charleston', country: '美国', pinyin: 'CLES' },
  { name: '萨凡纳', english: 'Savannah', country: '美国', pinyin: 'SFN' },
  { name: '诺福克', english: 'Norfolk', country: '美国', pinyin: 'NFK' },
  { name: '巴尔的摩', english: 'Baltimore', country: '美国', pinyin: 'BEM' },
  { name: '纽约', english: 'New York', country: '美国', pinyin: 'NY' },
  { name: '波士顿', english: 'Boston', country: '美国', pinyin: 'BSD' },
  { name: '温哥华', english: 'Vancouver', country: '加拿大', pinyin: 'WH' },
  { name: '蒙特利尔', english: 'Montreal', country: '加拿大', pinyin: 'MTEL' },
  { name: '多伦多', english: 'Toronto', country: '加拿大', pinyin: 'DL' },
  { name: '哈利法克斯', english: 'Halifax', country: '加拿大', pinyin: 'HLFX' },
  { name: '圣约翰', english: 'Saint John', country: '加拿大', pinyin: 'SYHN' },
  { name: '墨西哥城', english: 'Mexico City', country: '墨西哥', pinyin: 'MXC' },
  { name: '曼萨尼约', english: 'Manzanillo', country: '墨西哥', pinyin: 'MSN' },
  { name: '拉萨罗卡德纳斯', english: 'Lazaro Cardenas', country: '墨西哥', pinyin: 'LSLKDN' },
  { name: '韦拉克鲁斯', english: 'Veracruz', country: '墨西哥', pinyin: 'WLKS' },
  { name: '坦皮科', english: 'Tampico', country: '墨西哥', pinyin: 'TPK' },
  { name: '巴拿马城', english: 'Panama City', country: '巴拿马', pinyin: 'BNMC' },
  { name: '科隆', english: 'Colon', country: '巴拿马', pinyin: 'KL' },
  { name: '巴尔博亚', english: 'Balboa', country: '巴拿马', pinyin: 'BBY' },
  { name: '圣胡安', english: 'San Juan', country: '波多黎各', pinyin: 'SHN' },
  { name: '哈瓦那', english: 'Havana', country: '古巴', pinyin: 'HWN' },
  { name: '圣多明各', english: 'Santo Domingo', country: '多米尼加', pinyin: 'SDMG' },
  { name: '金斯敦', english: 'Kingston', country: '牙买加', pinyin: 'JSD' },
  { name: '太子港', english: 'Port au Prince', country: '海地', pinyin: 'TZG' },
  { name: '波哥大', english: 'Bogota', country: '哥伦比亚', pinyin: 'BGD' },
  { name: '卡塔赫纳', english: 'Cartagena', country: '哥伦比亚', pinyin: 'KTGN' },
  { name: '布埃纳文图拉', english: 'Buenaventura', country: '哥伦比亚', pinyin: 'BWN' },
  { name: '圣玛尔塔', english: 'Santa Marta', country: '哥伦比亚', pinyin: 'SM' },
  { name: '瓜亚基尔', english: 'Guayaquil', country: '厄瓜多尔', pinyin: 'GYQ' },
  { name: '曼塔', english: 'Manta', country: '厄瓜多尔', pinyin: 'MT' },
  { name: '利马', english: 'Lima', country: '秘鲁', pinyin: 'LM' },
  { name: '卡亚俄', english: 'Callao', country: '秘鲁', pinyin: 'KY' },
  { name: '皮斯科', english: 'Pisco', country: '秘鲁', pinyin: 'PSK' },
  { name: '伊基托斯', english: 'Iquitos', country: '秘鲁', pinyin: 'YKTS' },
  { name: '瓦尔帕莱索', english: 'Valparaiso', country: '智利', pinyin: 'WEPLS' },
  { name: '圣安东尼奥', english: 'San Antonio', country: '智利', pinyin: 'SADNG' },
  { name: '伊基克', english: 'Iquique', country: '智利', pinyin: 'YKK' },
  { name: '安托法加斯塔', english: 'Antofagasta', country: '智利', pinyin: 'ATFJST' },
  { name: '蒙特港', english: 'Puerto Montt', country: '智利', pinyin: 'MTG' },
  { name: '蓬塔阿雷纳斯', english: 'Punta Arenas', country: '智利', pinyin: 'PTALS' },
  { name: '布宜诺斯艾利斯', english: 'Buenos Aires', country: '阿根廷', pinyin: 'BYNS' },
  { name: '罗萨里奥', english: 'Rosario', country: '阿根廷', pinyin: 'LSL' },
  { name: '拉普拉塔', english: 'La Plata', country: '阿根廷', pinyin: 'LPLT' },
  { name: '布兰卡港', english: 'Bahia Blanca', country: '阿根廷', pinyin: 'BLKG' },
  { name: '乌斯怀亚', english: 'Ushuaia', country: '阿根廷', pinyin: 'WSHY' },
  { name: '蒙得维的亚', english: 'Montevideo', country: '乌拉圭', pinyin: 'MDWDY' },
  { name: '里约热内卢', english: 'Rio de Janeiro', country: '巴西', pinyin: 'LYRL' },
  { name: '桑托斯', english: 'Santos', country: '巴西', pinyin: 'STS' },
  { name: '帕拉那瓜', english: 'Paranagua', country: '巴西', pinyin: 'PLNG' },
  { name: '福塔雷萨', english: 'Fortaleza', country: '巴西', pinyin: 'FTLS' },
  { name: '累西腓', english: 'Recife', country: '巴西', pinyin: 'LXF' },
  { name: '萨尔瓦多', english: 'Salvador', country: '巴西', pinyin: 'SEWD' },
  { name: '维多利亚', english: 'Vitoria', country: '巴西', pinyin: 'WDLY' },
  { name: '圣保罗', english: 'Sao Paulo', country: '巴西', pinyin: 'SL' },
  { name: '阿雷格里港', english: 'Porto Alegre', country: '巴西', pinyin: 'ALG' },
  { name: '玛瑙斯', english: 'Manaus', country: '巴西', pinyin: 'MNS' },
  { name: '马卡帕', english: 'Macapa', country: '巴西', pinyin: 'MKB' },
  { name: '贝伦', english: 'Belem', country: '巴西', pinyin: 'BL' },
];

// 大洋洲港口
const oceaniaPorts = [
  { name: '悉尼', english: 'Sydney', country: '澳大利亚', pinyin: 'XN' },
  { name: '墨尔本', english: 'Melbourne', country: '澳大利亚', pinyin: 'MBE' },
  { name: '布里斯班', english: 'Brisbane', country: '澳大利亚', pinyin: 'BLSB' },
  { name: '弗里曼特尔', english: 'Fremantle', country: '澳大利亚', pinyin: 'FLMT' },
  { name: '阿德莱德', english: 'Adelaide', country: '澳大利亚', pinyin: 'ADE' },
  { name: '纽卡斯尔', english: 'Newcastle', country: '澳大利亚', pinyin: 'NKSE' },
  { name: '汤斯维尔', english: 'Townsville', country: '澳大利亚', pinyin: 'TWSW' },
  { name: '黑德兰港', english: 'Port Hedland', country: '澳大利亚', pinyin: 'HDG' },
  { name: '达尔文', english: 'Darwin', country: '澳大利亚', pinyin: 'DW' },
  { name: '霍巴特', english: 'Hobart', country: '澳大利亚', pinyin: 'HBT' },
  { name: '奥克兰', english: 'Auckland', country: '新西兰', pinyin: 'AKL' },
  { name: '惠灵顿', english: 'Wellington', country: '新西兰', pinyin: 'HL' },
  { name: '利特尔顿', english: 'Lyttelton', country: '新西兰', pinyin: 'LTEL' },
  { name: '陶朗阿', english: 'Tauranga', country: '新西兰', pinyin: 'TLA' },
  { name: '纳皮尔', english: 'Napier', country: '新西兰', pinyin: 'NP' },
  { name: '内皮尔', english: 'Napier', country: '新西兰', pinyin: 'NP' },
  { name: '苏瓦', english: 'Suva', country: '斐济', pinyin: 'SW' },
  { name: '努美阿', english: 'Noumea', country: '新喀里多尼亚', pinyin: 'NM' },
  { name: '阿皮亚', english: 'Apia', country: '萨摩亚', pinyin: 'APY' },
  { name: '莫尔兹比港', english: 'Port Moresby', country: '巴布亚新几内亚', pinyin: 'MZB' },
  { name: '莱城', english: 'Lae', country: '巴布亚新几内亚', pinyin: 'LC' },
];

const allPorts = [
  ...chinaPorts,
  ...southeastAsiaPorts,
  ...eastAsiaPorts,
  ...middleEastPorts,
  ...southAsiaPorts,
  ...europePorts,
  ...africaPorts,
  ...americasPorts,
  ...oceaniaPorts,
];

async function main() {
  console.log('开始导入世界港口数据...');
  
  for (const port of allPorts) {
    await prisma.port.upsert({
      where: { name_country: { name: port.name, country: port.country } },
      update: {
        english: port.english,
        pinyin: port.pinyin,
      },
      create: {
        name: port.name,
        english: port.english,
        country: port.country,
        pinyin: port.pinyin,
      },
    });
  }

  console.log(`成功导入 ${allPorts.length} 个世界港口数据`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
