CREATE TABLE IF NOT EXISTS "Port" (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "english" VARCHAR(255),
    "country" VARCHAR(255) NOT NULL,
    "pinyin" VARCHAR(255),
    "code" VARCHAR(50),
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "Port_name_country_key" ON "Port"("name", "country");
CREATE INDEX IF NOT EXISTS "Port_name_idx" ON "Port"("name");
CREATE INDEX IF NOT EXISTS "Port_country_idx" ON "Port"("country");
CREATE INDEX IF NOT EXISTS "Port_pinyin_idx" ON "Port"("pinyin");

INSERT INTO "Port" ("name", "english", "country", "pinyin", "code") VALUES
('上海', 'Shanghai', '中国', 'shanghai', 'SHA'),
('宁波', 'Ningbo', '中国', 'ningbo', 'NGB'),
('天津', 'Tianjin', '中国', 'tianjin', 'TSN'),
('青岛', 'Qingdao', '中国', 'qingdao', 'TAO'),
('大连', 'Dalian', '中国', 'dalian', 'DLC'),
('广州', 'Guangzhou', '中国', 'guangzhou', 'CAN'),
('深圳', 'Shenzhen', '中国', 'shenzhen', 'SZX'),
('香港', 'Hong Kong', '中国', 'xianggang', 'HKG'),
('厦门', 'Xiamen', '中国', 'xiamen', 'XMN'),
('新加坡', 'Singapore', '新加坡', 'xinjiapo', 'SIN'),
('东京', 'Tokyo', '日本', 'dongjing', 'TYO'),
('釜山', 'Busan', '韩国', 'fushan', 'PUS'),
('迪拜', 'Dubai', '阿联酋', 'dibai', 'DXB'),
('鹿特丹', 'Rotterdam', '荷兰', 'lutedan', 'RTM'),
('汉堡', 'Hamburg', '德国', 'hanbao', 'HAM'),
('伦敦', 'London', '英国', 'lundun', 'LON'),
('纽约', 'New York', '美国', 'niuyue', 'NYC'),
('洛杉矶', 'Los Angeles', '美国', 'luoshanji', 'LAX'),
('悉尼', 'Sydney', '澳大利亚', 'xini', 'SYD'),
('温哥华', 'Vancouver', '加拿大', 'wengehua', 'YVR'),
('曼谷', 'Bangkok', '泰国', 'mangu', 'BKK'),
('马尼拉', 'Manila', '菲律宾', 'manila', 'MNL'),
('雅加达', 'Jakarta', '印度尼西亚', 'yajiada', 'JKT'),
('孟买', 'Mumbai', '印度', 'mengmai', 'BOM'),
('科伦坡', 'Colombo', '斯里兰卡', 'kelunpo', 'CMB'),
('吉达', 'Jeddah', '沙特阿拉伯', 'jida', 'JED'),
('苏伊士', 'Suez', '埃及', 'suyishi', 'SUZ'),
('热那亚', 'Genoa', '意大利', 'renaya', 'GOA'),
('马赛', 'Marseille', '法国', 'masai', 'MRS'),
('安特卫普', 'Antwerp', '比利时', 'anteweipu', 'ANR'),
('新加坡港', 'Singapore Port', '新加坡', 'xinjiapo gang', 'SGP'),
('神户', 'Kobe', '日本', 'shenhu', 'KOB'),
('仁川', 'Incheon', '韩国', 'renchuan', 'ICN'),
('横滨', 'Yokohama', '日本', 'hengbin', 'YOK'),
('大阪', 'Osaka', '日本', 'daban', 'OSK'),
('不来梅', 'Bremen', '德国', 'bulaimei', 'BRE'),
('南安普顿', 'Southampton', '英国', 'nan anputun', 'SOU'),
('阿姆斯特丹', 'Amsterdam', '荷兰', 'amusitedan', 'AMS'),
('哥本哈根', 'Copenhagen', '丹麦', 'gubenhaigen', 'CPH'),
('奥斯陆', 'Oslo', '挪威', 'aosilu', 'OSL'),
('斯德哥尔摩', 'Stockholm', '瑞典', 'sidegeer mo', 'STO'),
('赫尔辛基', 'Helsinki', '芬兰', 'heersinki', 'HEL'),
('里斯本', 'Lisbon', '葡萄牙', 'lisiben', 'LIS'),
('巴塞罗那', 'Barcelona', '西班牙', 'basailuona', 'BCN'),
('瓦伦西亚', 'Valencia', '西班牙', 'walunxiya', 'VLC'),
('卡萨布兰卡', 'Casablanca', '摩洛哥', 'kasabulanka', 'CMN'),
('开普敦', 'Cape Town', '南非', 'kaipu dun', 'CPT'),
('德班', 'Durban', '南非', 'deban', 'DUR'),
('迪拜港', 'Jebel Ali', '阿联酋', 'dibai gang', 'JEA'),
('阿布扎比', 'Abu Dhabi', '阿联酋', 'abuzhabi', 'AUH'),
('科威特', 'Kuwait', '科威特', 'kewait', 'KWI'),
('多哈', 'Doha', '卡塔尔', 'duoha', 'DOH'),
('卡拉奇', 'Karachi', '巴基斯坦', 'kalachi', 'KHI'),
('吉大港', 'Chittagong', '孟加拉国', 'jidagang', 'CGP'),
('仰光', 'Yangon', '缅甸', 'yangguang', 'RGN'),
('胡志明市', 'Ho Chi Minh', '越南', 'huzhiming shi', 'SGN'),
('海防', 'Haiphong', '越南', 'haifang', 'HPH'),
('岘港', 'Da Nang', '越南', 'xianggang', 'DAD'),
('槟城', 'Penang', '马来西亚', 'bingcheng', 'PEN'),
('巴生港', 'Port Klang', '马来西亚', 'basheng gang', 'PKG'),
('达尔文', 'Darwin', '澳大利亚', 'daerwen', 'DRW'),
('布里斯班', 'Brisbane', '澳大利亚', 'bulisiban', 'BNE'),
('奥克兰', 'Auckland', '新西兰', 'aokelan', 'AKL'),
('惠灵顿', 'Wellington', '新西兰', 'huilingdun', 'WLG'),
('火奴鲁鲁', 'Honolulu', '美国', 'huonolulu', 'HNL'),
('蒙特利尔', 'Montreal', '加拿大', 'mengtelier', 'YUL'),
('巴尔的摩', 'Baltimore', '美国', 'ba erde mo', 'BWI'),
('迈阿密', 'Miami', '美国', 'maiami', 'MIA'),
('休斯顿', 'Houston', '美国', 'xiuston', 'IAH'),
('圣保罗', 'Santos', '巴西', 'shengbaoluo', 'SSZ'),
('里约热内卢', 'Rio de Janeiro', '巴西', 'liyaoreineilu', 'GIG'),
('布宜诺斯艾利斯', 'Buenos Aires', '阿根廷', 'buyinuo silis', 'EZE'),
('巴拿马城', 'Panama City', '巴拿马', 'banama cheng', 'PTY'),
('直布罗陀', 'Gibraltar', '英国', 'zhibuluotuo', 'GIB'),
('伊斯坦布尔', 'Istanbul', '土耳其', 'yisitanbu er', 'IST'),
('特拉维夫', 'Tel Aviv', '以色列', 'telafu', 'TLV'),
('贝鲁特', 'Beirut', '黎巴嫩', 'beilute', 'BEY'),
('塞得港', 'Port Said', '埃及', 'saide gang', 'PSD'),
('上海港', 'Shanghai Port', '中国', 'shanghai gang', 'SHA'),
('宁波港', 'Ningbo-Zhoushan', '中国', 'ningbo gang', 'NGB'),
('天津港', 'Tianjin Port', '中国', 'tianjin gang', 'TSN'),
('青岛港', 'Qingdao Port', '中国', 'qingdao gang', 'TAO'),
('大连港', 'Dalian Port', '中国', 'dalian gang', 'DLC'),
('广州港', 'Guangzhou Port', '中国', 'guangzhou gang', 'CAN'),
('深圳港', 'Shenzhen Port', '中国', 'shenzhen gang', 'SZX'),
('香港港', 'Hong Kong Port', '中国', 'xianggang gang', 'HKG'),
('厦门港', 'Xiamen Port', '中国', 'xiamen gang', 'XMN'),
('福州', 'Fuzhou', '中国', 'fuzhou', 'FOC'),
('泉州', 'Quanzhou', '中国', 'quanzhou', 'JJN'),
('温州', 'Wenzhou', '中国', 'wenzhou', 'WNZ'),
('连云港', 'Lianyungang', '中国', 'lianyungang', 'LYG'),
('南京', 'Nanjing', '中国', 'nanjing', 'NKG'),
('武汉', 'Wuhan', '中国', 'wuhan', 'WUH'),
('重庆', 'Chongqing', '中国', 'chongqing', 'CKG'),
('杭州', 'Hangzhou', '中国', 'hangzhou', 'HGH'),
('苏州', 'Suzhou', '中国', 'suzhou', 'SZV'),
('无锡', 'Wuxi', '中国', 'wuxi', 'WUX'),
('南通', 'Nantong', '中国', 'nantong', 'NTG'),
('泰州', 'Taizhou', '中国', 'taizhou', 'HYN'),
('扬州', 'Yangzhou', '中国', 'yangzhou', 'YTY'),
('镇江', 'Zhenjiang', '中国', 'zhenjiang', 'ZKA'),
('合肥', 'Hefei', '中国', 'hefei', 'HFE'),
('芜湖', 'Wuhu', '中国', 'wuhu', 'WUH'),
('南昌', 'Nanchang', '中国', 'nanchang', 'KHN'),
('长沙', 'Changsha', '中国', 'changsha', 'CSX'),
('南宁', 'Nanning', '中国', 'nanning', 'NNG'),
('北海', 'Beihai', '中国', 'beihai', 'BHY'),
('钦州', 'Qinzhou', '中国', 'qinzhou', 'ZQZ'),
('防城港', 'Fangchenggang', '中国', 'fangchenggang', 'FCG'),
('海口', 'Haikou', '中国', 'haikou', 'HAK'),
('三亚', 'Sanya', '中国', 'sanya', 'SYX'),
('高雄', 'Kaohsiung', '中国台湾', 'gaoxiong', 'KHH'),
('基隆', 'Keelung', '中国台湾', 'jilong', 'KHH'),
('台中', 'Taichung', '中国台湾', 'taizhong', 'TXG'),
('台南', 'Tainan', '中国台湾', 'tainan', 'TNN'),
('花莲', 'Hualien', '中国台湾', 'hualian', 'HUN');
